const express = require('express')
const bodyParser = require('body-parser')
const mongoose = require('mongoose')
const profilerouter = require('./routers/profile')
const verificationrouter = require('./routers/verification')
const taskRouter = require('./routers/task')
const routergoogle = require('./google')
const routeruser = require('./routers/user')
const routergooglelogin = require('./googleLogin')

require('dotenv').config()
const port = process.env.PORT || 3001  
const app = express()
const uri = process.env.URI
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use('/user', routeruser)
app.use('/profile', profilerouter)
app.use('/task', taskRouter)
app.use ('/', verificationrouter)
app.use('/login', routergooglelogin)
app.use('/', routergoogle)
mongoose.connect(uri, {dbName:'tnoti'}).then(()=>console.log('Connected to mongodb')).catch((err) =>console.log(`An error occured\n${err}`))
app.get('/', (req, res)=>res.send('application set up'))
app.listen(port, ()=> console.log(`The app is running at http://localhost:${port}`))